spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: # RDS
    username: # Username
    password: # Password
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
    show-sql: true
  data:
    redis:
      host: # AWS Redis
      port: 6379
    cache:
      type: redis
  jwt:
    token:
      secretKey: # secret key
      expiration:
        access: 7200000 # 2시간
        refresh: 1209600000 # 2주
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
